#!/usr/bin/env bash

# Proxy commands for the bitwarden CLI, intercepting them to get or set a
# session token for seamless use between shells and other programs.
# Make sure this script is in your $PATH, so you can simply run 'bw' like you
# normally would.

# If you have a $HOME/bin dir that is at the front of your $PATH, you should be
# able to use this as an install method:
# curl https://raw.githubusercontent.com/mjslabs/bitagent/master/examples/bw > $HOME/bin/bw && chmod 0755 $HOME/bin/bw

# Installation of the bitwarden CLI
bwcmd="${HOME}/bin/bwcli"
# Default socket location
basock="${HOME}/.bitagent.sock"
# This assumes you've run a `go install`
bitagent="${GOBIN:-${HOME}/go/bin}/bitagent $basock"

if [[ ! -e $basock ]]; then
  $bitagent 1>/dev/null & disown
fi

if [[ $1 == "unlock" || $1 == "login" ]]; then
  unlockOut=$($bwcmd $1)
  <<< $unlockOut grep -q BW_SESSION
  if [[ $? == "0" ]]; then
    echo "$1 successful"
    echo "P"$(<<< $unlockOut tr -d '\n' | sed -e 's/^.*BW_SESSION="\(.*\)".*$/\1/') | nc -U $basock -N
  else
    echo "$1 failed"
    echo $unlockOut
  fi
  exit
else
  export BW_SESSION="$(echo G | nc -U $basock -N)"
  if [[ $BW_SESSION == "" ]]; then
    # Avoids "Session key is invalid." being sent to the terminal
    unset BW_SESSION
  fi
  $bwcmd $*
 fi
